---
- name: Configure compiler server
  hosts: compiler

  tasks:
  - name: install git
    apt:
      name: git
      state: present

  - name: Clone source code from git
    git:
      repo: https://github.com/ag4544/boxfuse-sample.git
      dest: /var/boxfuse-sample/

  - name: Install java
    apt:
      name: default-jdk
      state: present

  - name: install maven
    apt:
      name: maven
      state: present
      
  - name: Compile from source
    shell: mvn package
    args:
      chdir: /var/boxfuse-sample/

- name: Configure web server
  hosts: webserver

  tasks:
  - name: Install java
    apt:
      name: default-jdk
      state: present

  - name: Install tomcat
    apt:
      name: tomcat9
      state: present

  - name: Remove ROOT dir from tomcat 
    file:
      path: /var/lib/tomcat9/webapps/ROOT
      state: absent

  - name: RSYNC boxfuse war from compiler to webserver
    shell: rsync -a {{ groups.compiler | first }}:/var/boxfuse-sample/target/hello-1.0.war /var/lib/tomcat9/webapps/ROOT.war

  - name: restart tomcat9
    service:
      name: tomcat9
      state: restarted
